title:            "ochieng'"
url:              http://nicholasgot.com
permalink:        pretty
highlighter:      pygments
markdown:         kramdown
google_analytics: UA-21332781-7
timezone:         Europe/Stockholm
gems:
  - jemoji
  - jekyll-mentions
